create table if not exists public.mentorships (
  id bigint generated by default as identity primary key,
  mentor_id uuid not null references auth.users(id) on delete cascade,
  apprentice_id uuid not null references auth.users(id) on delete cascade,
  status text not null check (status in ('pending', 'accepted', 'rejected', 'cancelled', 'ended')),
  requested_at timestamptz not null default now(),
  responded_at timestamptz,
  ended_at timestamptz,
  check (mentor_id <> apprentice_id)
);

create unique index if not exists mentorships_active_pair_key
on public.mentorships (mentor_id, apprentice_id)
where status in ('pending', 'accepted');

create unique index if not exists mentorships_one_accepted_mentor_per_apprentice
on public.mentorships (apprentice_id)
where status = 'accepted';

create index if not exists mentorships_mentor_status_idx on public.mentorships (mentor_id, status);
create index if not exists mentorships_apprentice_status_idx on public.mentorships (apprentice_id, status);

alter table public.mentorships enable row level security;
revoke all on table public.mentorships from public, anon, authenticated;
grant select on table public.mentorships to anon, authenticated;

drop policy if exists "accepted mentorships are public and requests belong to parties" on public.mentorships;
create policy "accepted mentorships are public and requests belong to parties"
on public.mentorships for select
using (status = 'accepted' or auth.uid() in (mentor_id, apprentice_id));

create or replace function public.request_mentorship(p_mentor_id uuid)
returns bigint language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user_id uuid := auth.uid(); v_id bigint;
begin
  if v_user_id is null then raise exception 'authentication required'; end if;
  if p_mentor_id = v_user_id then raise exception 'cannot mentor yourself'; end if;
  if exists (select 1 from public.mentorships where apprentice_id = v_user_id and status = 'accepted') then
    raise exception 'an accepted mentor already exists';
  end if;
  if exists (
    with recursive descendants(id) as (
      select apprentice_id from public.mentorships where mentor_id = v_user_id and status = 'accepted'
      union
      select m.apprentice_id from public.mentorships m join descendants d on m.mentor_id = d.id where m.status = 'accepted'
    ) select 1 from descendants where id = p_mentor_id
  ) then raise exception 'cyclic mentorship is not allowed'; end if;
  insert into public.mentorships(mentor_id, apprentice_id, status)
  values (p_mentor_id, v_user_id, 'pending') returning id into v_id;
  return v_id;
end; $$;

create or replace function public.respond_to_mentorship(p_request_id bigint, p_accept boolean)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user_id uuid := auth.uid(); v_request public.mentorships%rowtype;
begin
  select * into v_request from public.mentorships where id = p_request_id for update;
  if v_user_id is null or v_request.mentor_id <> v_user_id or v_request.status <> 'pending' then
    raise exception 'request cannot be changed';
  end if;
  if p_accept and exists (select 1 from public.mentorships where apprentice_id = v_request.apprentice_id and status = 'accepted') then
    raise exception 'the apprentice already has a mentor';
  end if;
  update public.mentorships set status = case when p_accept then 'accepted' else 'rejected' end, responded_at = now()
  where id = p_request_id;
end; $$;

create or replace function public.close_mentorship(p_request_id bigint)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user_id uuid := auth.uid();
begin
  update public.mentorships
  set status = case when status = 'pending' then 'cancelled' else 'ended' end,
      ended_at = now()
  where id = p_request_id
    and auth.uid() in (mentor_id, apprentice_id)
    and status in ('pending', 'accepted');
  if v_user_id is null or not found then raise exception 'relationship cannot be changed'; end if;
end; $$;

revoke all on function public.request_mentorship(uuid) from public, anon;
revoke all on function public.respond_to_mentorship(bigint, boolean) from public, anon;
revoke all on function public.close_mentorship(bigint) from public, anon;
grant execute on function public.request_mentorship(uuid) to authenticated;
grant execute on function public.respond_to_mentorship(bigint, boolean) to authenticated;
grant execute on function public.close_mentorship(bigint) to authenticated;
