create table if not exists public.coin_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance bigint not null default 0 check (balance >= 0), updated_at timestamptz not null default now()
);
create table if not exists public.coin_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount bigint not null check (amount <> 0), balance_after bigint not null check (balance_after >= 0),
  reason text not null, reference_key text not null, created_at timestamptz not null default now(),
  unique(user_id, reference_key)
);
create table if not exists public.shop_products (
  id text primary key, name text not null, description text not null,
  item_kind text not null check(item_kind in ('theme','frame')), item_id text not null,
  price bigint not null check(price >= 0), is_public boolean not null default true, display_order integer not null default 0,
  unique(item_kind, item_id)
);
create table if not exists public.shop_purchases (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null references public.shop_products(id), purchased_at timestamptz not null default now(),
  primary key(user_id, product_id)
);
create table if not exists public.login_bonus_claims (
  user_id uuid not null references auth.users(id) on delete cascade,
  claim_date date not null, amount bigint not null check(amount > 0), claimed_at timestamptz not null default now(),
  primary key(user_id, claim_date)
);
create table if not exists public.daily_task_catalog (
  id text primary key, name text not null, description text not null, event_kind text not null,
  target_count integer not null check(target_count > 0), reward bigint not null check(reward > 0), is_public boolean not null default true
);
create table if not exists public.daily_task_claims (
  user_id uuid not null references auth.users(id) on delete cascade,
  task_id text not null references public.daily_task_catalog(id), claim_date date not null,
  claimed_at timestamptz not null default now(), primary key(user_id, task_id, claim_date)
);

alter table public.coin_wallets enable row level security; alter table public.coin_ledger enable row level security;
alter table public.shop_products enable row level security; alter table public.shop_purchases enable row level security;
alter table public.login_bonus_claims enable row level security; alter table public.daily_task_catalog enable row level security;
alter table public.daily_task_claims enable row level security;
revoke all on table public.coin_wallets, public.coin_ledger, public.shop_products, public.shop_purchases,
 public.login_bonus_claims, public.daily_task_catalog, public.daily_task_claims from public, anon, authenticated;
grant select on table public.shop_products, public.daily_task_catalog to anon, authenticated;
grant select on table public.coin_wallets, public.coin_ledger, public.shop_purchases, public.login_bonus_claims, public.daily_task_claims to authenticated;
create policy "own wallet" on public.coin_wallets for select using(auth.uid()=user_id);
create policy "own ledger" on public.coin_ledger for select using(auth.uid()=user_id);
create policy "public products" on public.shop_products for select using(is_public);
create policy "own purchases" on public.shop_purchases for select using(auth.uid()=user_id);
create policy "own bonus claims" on public.login_bonus_claims for select using(auth.uid()=user_id);
create policy "public daily tasks" on public.daily_task_catalog for select using(is_public);
create policy "own daily claims" on public.daily_task_claims for select using(auth.uid()=user_id);

insert into public.shop_products(id,name,description,item_kind,item_id,price,display_order) values
 ('theme-sakura','テーマ・桜','淡い桜色のテーマ','theme','sakura',300,10),
 ('theme-yoi','テーマ・宵','深い藍色のテーマ','theme','yoi',300,20),
 ('theme-washi','テーマ・和紙','静かな和紙色のテーマ','theme','washi',300,30),
 ('frame-gold','フレーム・金輪','控えめな金色の輪','frame','gold-ring',200,40),
 ('frame-sakura','フレーム・桜輪','桜色の輪','frame','sakura-ring',200,50)
on conflict(id) do update set name=excluded.name,description=excluded.description,price=excluded.price,display_order=excluded.display_order;
insert into public.daily_task_catalog(id,name,description,event_kind,target_count,reward) values
 ('post-one','今日の一句','俳句を1句投稿する','haiku',1,20),
 ('like-one','雅をひとつ','他の句へ雅を1回贈る','like',1,10),
 ('utaawase-one','歌合初め','歌合へ1回参加する','utaawase',1,30)
on conflict(id) do update set name=excluded.name,description=excluded.description,target_count=excluded.target_count,reward=excluded.reward;

create or replace function public.ensure_my_wallet() returns bigint language plpgsql security definer set search_path=public,pg_temp as $$
declare v uuid:=auth.uid(); b bigint;
begin if v is null then raise exception 'authentication required'; end if;
 insert into public.coin_wallets(user_id) values(v) on conflict do nothing;
 select balance into b from public.coin_wallets where user_id=v; return b; end $$;

create or replace function public.claim_daily_login_bonus() returns bigint language plpgsql security definer set search_path=public,pg_temp as $$
declare v uuid:=auth.uid(); d date:=(now() at time zone 'Asia/Tokyo')::date; reward bigint:=30; b bigint;
begin if v is null then raise exception 'authentication required'; end if;
 insert into public.login_bonus_claims(user_id,claim_date,amount) values(v,d,reward) on conflict do nothing;
 if not found then return (select balance from public.coin_wallets where user_id=v); end if;
 insert into public.coin_wallets(user_id,balance) values(v,reward) on conflict(user_id) do update set balance=coin_wallets.balance+reward,updated_at=now() returning balance into b;
 insert into public.coin_ledger(user_id,amount,balance_after,reason,reference_key) values(v,reward,b,'login_bonus','login:'||d); return b; end $$;

create or replace function public.purchase_shop_product(p_product_id text) returns bigint language plpgsql security definer set search_path=public,pg_temp as $$
declare v uuid:=auth.uid(); p public.shop_products%rowtype; b bigint;
begin if v is null then raise exception 'authentication required'; end if;
 select * into p from public.shop_products where id=p_product_id and is_public for share; if not found then raise exception 'product not found'; end if;
 insert into public.coin_wallets(user_id) values(v) on conflict do nothing; select balance into b from public.coin_wallets where user_id=v for update;
 if exists(select 1 from public.shop_purchases where user_id=v and product_id=p.id) then raise exception 'already purchased'; end if;
 if b<p.price then raise exception 'insufficient balance'; end if; b:=b-p.price;
 update public.coin_wallets set balance=b,updated_at=now() where user_id=v;
 insert into public.shop_purchases(user_id,product_id) values(v,p.id);
 if p.item_kind='theme' then insert into public.user_themes(user_id,theme_id) values(v,p.item_id) on conflict do nothing;
 else insert into public.user_avatar_frames(user_id,frame_id) values(v,p.item_id) on conflict do nothing; end if;
 insert into public.coin_ledger(user_id,amount,balance_after,reason,reference_key) values(v,-p.price,b,'shop_purchase','purchase:'||p.id); return b; end $$;

create or replace function public.claim_daily_task(p_task_id text) returns bigint language plpgsql security definer set search_path=public,pg_temp as $$
declare v uuid:=auth.uid(); d date:=(now() at time zone 'Asia/Tokyo')::date; start_at timestamptz; finish_at timestamptz; t public.daily_task_catalog%rowtype; progress bigint; b bigint;
begin if v is null then raise exception 'authentication required'; end if;
 start_at:=(d::timestamp at time zone 'Asia/Tokyo'); finish_at:=start_at+interval '1 day';
 select * into t from public.daily_task_catalog where id=p_task_id and is_public; if not found then raise exception 'task not found'; end if;
 progress:=case t.event_kind
  when 'haiku' then (select count(*) from public.haikus_2 where user_id=v and created_at>=start_at and created_at<finish_at)
  when 'like' then (select count(*) from public.likes_2 where user_id=v and created_at>=start_at and created_at<finish_at)
  when 'utaawase' then (select count(*) from public.utaawase_members where user_id=v and joined_at>=start_at and joined_at<finish_at)
  else 0 end;
 if progress<t.target_count then raise exception 'task is not complete'; end if;
 insert into public.daily_task_claims(user_id,task_id,claim_date) values(v,t.id,d) on conflict do nothing; if not found then raise exception 'reward already claimed'; end if;
 insert into public.coin_wallets(user_id,balance) values(v,t.reward) on conflict(user_id) do update set balance=coin_wallets.balance+t.reward,updated_at=now() returning balance into b;
 insert into public.coin_ledger(user_id,amount,balance_after,reason,reference_key) values(v,t.reward,b,'daily_task','task:'||t.id||':'||d); return b; end $$;

revoke all on function public.ensure_my_wallet(), public.claim_daily_login_bonus(), public.purchase_shop_product(text), public.claim_daily_task(text) from public,anon;
grant execute on function public.ensure_my_wallet(), public.claim_daily_login_bonus(), public.purchase_shop_product(text), public.claim_daily_task(text) to authenticated;
